package com.example.myapplication.db;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

/**
 * This class defines the structure of the 'user' table in the database.
 * It includes information about the user's association with an employee, their username, and password.
 * <p>
 * Authors: Cedric De Leon, Sergei Borja
 * Since: 2023.11.03
 */
@Entity(tableName = "user", foreignKeys = {@ForeignKey(entity = Employee.class, parentColumns = {"id"}, childColumns = {"employee_id"}, onDelete = ForeignKey.CASCADE)})
public class User {
    // Unique identifier for each user, auto-generated by the database.
    @PrimaryKey(autoGenerate = true)
    public int id;

    // Foreign key referencing the employee associated with this user account.
    @ColumnInfo(name = "employee_id", index = true)
    public int employeeId;

    // Username for user authentication.
    @ColumnInfo(name = "user_name")
    public String userName;

    // Password for user authentication.
    @ColumnInfo(name = "password")
    public String password;

    // Default constructor.
    public User() {
    }

    // Constructors used for creating instances of User.
    @Ignore
    public User(int employeeId, String userName, String password) {
        this.employeeId = employeeId;
        this.userName = userName;
        this.password = password;
    }
}
